spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veseliyprikol
    password: ovedet92
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  application:
    name: veseliyprikol
